# Generated by Django 4.1.3 on 2023-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_intr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
